// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller

import { application } from "./application"

import BooksController from "./books_controller.js"
application.register("books", BooksController)

import DropdownController from "./dropdown_controller.js"
application.register("dropdown", DropdownController)


import RatingsController from "./ratings_controller.js"
application.register("ratings", RatingsController)
