version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.7.1
    - 12.8.0
    - 12.8.1
    - 12.8.3
    - 13.0.10
    - 13.0.16
    - 13.0.6
    - 13.1.2
  - dependency-name: react-query
    versions:
    - 3.11.0
    - 3.12.0
    - 3.12.1
    - 3.13.0
    - 3.13.4
    - 3.13.6
  - dependency-name: netlify-cli
    versions:
    - 3.10.6
    - 3.13.5
    - 3.13.7
  - dependency-name: husky
    versions:
    - 5.1.2
    - 5.1.3
    - 5.2.0
  - dependency-name: core-js
    versions:
    - 3.9.1
  - dependency-name: node-notifier
    versions:
    - 8.0.1
- package-ecosystem: npm
  directory: "/functions"
  schedule:
    interval: weekly
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: faunadb
    versions:
    - 4.1.0
    - 4.1.1
    - 4.1.3
