require:
  - rubocop

Naming/VariableNumber:
  Enabled: false

AllCops:
  NewCops: enable
  Exclude:
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'lib/tasks/*'
    - 'script/**/*'
    - 'test/**/*'
    - 'bin/{rails,rake}'
    - !ruby/regexp /old_and_unused\.rb$/
    - 'vendor/bundle/**/*'